export const FULLCALENDAR_CATEGORY_OPEN_GOV = "OpenGov";
export const FULLCALENDAR_CATEGORY_DEMOCRACY = "Democracy";
export const FULLCALENDAR_CATEGORY_TREASURY = "Treasury";
export const FULLCALENDAR_CATEGORY_COLLECTIVES = "Collectives";
export const FULLCALENDAR_CATEGORY_OTHERS = "Others";
export const FULLCALENDAR_CATEGORY_STAKING = "Staking";
export const FULLCALENDAR_CATEGORY_SCHEDULER = "Scheduler";
export const FULLCALENDAR_CATEGORY_SOCIETY = "Society";
export const FULLCALENDAR_CATEGORY_PARACHAIN = "Parachain";
export const FULLCALENDAR_CATEGORY_USER = "User Event";

export const FULLCALENDAR_CATEGORY_COLORS = {
  [FULLCALENDAR_CATEGORY_OPEN_GOV]: "var(--blue500)",
  [FULLCALENDAR_CATEGORY_DEMOCRACY]: "var(--pink500)",
  [FULLCALENDAR_CATEGORY_TREASURY]: "var(--orange500)",
  [FULLCALENDAR_CATEGORY_COLLECTIVES]: "var(--green500)",
  [FULLCALENDAR_CATEGORY_OTHERS]: "var(--textTertiary)",
  [FULLCALENDAR_CATEGORY_STAKING]: "var(--textTertiary)",
  [FULLCALENDAR_CATEGORY_SCHEDULER]: "var(--textTertiary)",
  [FULLCALENDAR_CATEGORY_SOCIETY]: "var(--textTertiary)",
  [FULLCALENDAR_CATEGORY_PARACHAIN]: "var(--textTertiary)",
  [FULLCALENDAR_CATEGORY_USER]: "var(--textTertiary)",
};

export const FULLCALENDAR_CATEGORIES = [
  FULLCALENDAR_CATEGORY_OPEN_GOV,
  FULLCALENDAR_CATEGORY_DEMOCRACY,
  FULLCALENDAR_CATEGORY_TREASURY,
  FULLCALENDAR_CATEGORY_COLLECTIVES,
  FULLCALENDAR_CATEGORY_OTHERS,
  FULLCALENDAR_CATEGORY_STAKING,
  FULLCALENDAR_CATEGORY_SCHEDULER,
  FULLCALENDAR_CATEGORY_SOCIETY,
  FULLCALENDAR_CATEGORY_PARACHAIN,
  FULLCALENDAR_CATEGORY_USER,
];
