export const FULLCALENDAR_CATEGORY_OPEN_GOV = "OpenGov";
export const FULLCALENDAR_CATEGORY_DEMOCRACY = "Democracy";
export const FULLCALENDAR_CATEGORY_TREASURY = "Treasury";
export const FULLCALENDAR_CATEGORY_COLLECTIVES = "Collectives";

export const FULLCALENDAR_CATEGORY_COLORS = {
  [FULLCALENDAR_CATEGORY_OPEN_GOV]: "secondaryBlue500",
  [FULLCALENDAR_CATEGORY_DEMOCRACY]: "secondaryPink500",
  [FULLCALENDAR_CATEGORY_TREASURY]: "secondaryYellow500",
  [FULLCALENDAR_CATEGORY_COLLECTIVES]: "textTertiary",
};

export const FULLCALENDAR_CATEGORIES = [
  FULLCALENDAR_CATEGORY_OPEN_GOV,
  FULLCALENDAR_CATEGORY_DEMOCRACY,
  FULLCALENDAR_CATEGORY_TREASURY,
  FULLCALENDAR_CATEGORY_COLLECTIVES,
];
