export const FULLCALENDAR_CATEGORY_OPEN_GOV = "OpenGov";
export const FULLCALENDAR_CATEGORY_DEMOCRACY = "Democracy";
export const FULLCALENDAR_CATEGORY_TREASURY = "Treasury";
export const FULLCALENDAR_CATEGORY_COLLECTIVES = "Collectives";
export const FULLCALENDAR_CATEGORY_OTHERS = "Others";
export const FULLCALENDAR_CATEGORY_STAKING = "Staking";
export const FULLCALENDAR_CATEGORY_SCHEDULER = "Scheduler";
export const FULLCALENDAR_CATEGORY_SOCIETY = "Society";
export const FULLCALENDAR_CATEGORY_PARACHAIN = "Parachain";
export const FULLCALENDAR_CATEGORY_USER = "User Event";

export const FULLCALENDAR_CATEGORY_COLORS = {
  [FULLCALENDAR_CATEGORY_OPEN_GOV]: "secondaryBlue500",
  [FULLCALENDAR_CATEGORY_DEMOCRACY]: "secondaryPink500",
  [FULLCALENDAR_CATEGORY_TREASURY]: "secondaryYellow500",
  [FULLCALENDAR_CATEGORY_COLLECTIVES]: "secondaryGreen500",
  [FULLCALENDAR_CATEGORY_OTHERS]: "textTertiary",
  [FULLCALENDAR_CATEGORY_STAKING]: "textTertiary",
  [FULLCALENDAR_CATEGORY_SCHEDULER]: "textTertiary",
  [FULLCALENDAR_CATEGORY_SOCIETY]: "textTertiary",
  [FULLCALENDAR_CATEGORY_PARACHAIN]: "textTertiary",
  [FULLCALENDAR_CATEGORY_USER]: "textTertiary",
};

export const FULLCALENDAR_CATEGORIES = [
  FULLCALENDAR_CATEGORY_OPEN_GOV,
  FULLCALENDAR_CATEGORY_DEMOCRACY,
  FULLCALENDAR_CATEGORY_TREASURY,
  FULLCALENDAR_CATEGORY_COLLECTIVES,
  FULLCALENDAR_CATEGORY_OTHERS,
  FULLCALENDAR_CATEGORY_STAKING,
  FULLCALENDAR_CATEGORY_SCHEDULER,
  FULLCALENDAR_CATEGORY_SOCIETY,
  FULLCALENDAR_CATEGORY_PARACHAIN,
  FULLCALENDAR_CATEGORY_USER,
];
