const Chains = {
  polkadot: "polkadot",
  kusama: "kusama",
  karura: "karura",
  acala: "acala",
  phala: "phala",
  khala: "khala",
  substrate: "substrate",
  basilisk: "basilisk",
  hydradx: "hydradx",
  kabocha: "kabocha",
  bifrost: "bifrost",
  kintsugi: "kintsugi",
  interlay: "interlay",
  polkadex: "polkadex",
  crust: "crust",
  calamari: "calamari",
  turing: "turing",
  crab: "crab",
  centrifuge: "centrifuge",
  litmus: "litmus",
  zeitgeist: "zeitgeist",
  altair: "altair",
  development: "development",
  rococo: "rococo",
  litentry: "litentry",
  westend: "westend",
  "westend-collectives": "westend-collectives",
  collectives: "collectives",
  darwinia2: "darwinia2",
  "bifrost-polkadot": "bifrost-polkadot",
};

export default Chains;
