const Chains = {
  polkadot: "polkadot",
  kusama: "kusama",
  karura: "karura",
  acala: "acala",
  phala: "phala",
  khala: "khala",
  substrate: "substrate",
  basilisk: "basilisk",
  kabocha: "kabocha",
  bifrost: "bifrost",
  kintsugi: "kintsugi",
  interlay: "interlay",
  polkadex: "polkadex",
  crust: "crust",
  calamari: "calamari",
  turing: "turing",
  crab: "crab",
  centrifuge: "centrifuge",
  litmus: "litmus",
  zeitgeist: "zeitgeist",
  altair: "altair",
};

export default Chains;
