const businessCategory = {
  treasuryProposals: "Treasury Proposals",
  treasuryTips: "Tips",
  treasuryBounties: "Treasury Bounties",
  treasuryChildBounties: "Treasury Child Bounties",
  councilMotions: "Council Motions",
  treasuryCouncilMotions: "Treasury Council Motions",
  tcProposals: "Tech. Comm. Proposals",
  democracyProposals: "Democracy Public Proposals",
  democracyExternals: "Democracy External Proposals",
  democracyReferenda: "Referenda",
  collective: "collective",
  polkassemblyDiscussions: "Polkassembly Discussions",
  discussions: "Discussions",
  openGovReferenda: "OpenGov Referenda",
  fellowship: "Fellowship",
  financialMotions: "Financial Motions",
  advisoryMotions: "Advisory Motions",
  allianceMotions: "Alliance Motions",
  allianceAnnouncements: "Alliance Announcements",
  openTechCommitteeProposals: "Open Tech. Comm. Proposals",
};

export const detailPageCategory = {
  POST: "post",
  PA_POST: "polkassembly/post",
  COUNCIL_MOTION: "council/motions",
  FINANCIAL_MOTION: "financial-council/motion",
  TECH_COMM_MOTION: "techcomm/proposals",
  DEMOCRACY_REFERENDUM: "democracy/referenda",
  DEMOCRACY_EXTERNAL: "democracy/externals",
  DEMOCRACY_PROPOSAL: "democracy/proposals",
  TREASURY_PROPOSAL: "treasury/proposals",
  TREASURY_BOUNTY: "treasury/bounties",
  TREASURY_CHILD_BOUNTY: "treasury/child-bounties",
  TREASURY_TIP: "treasury/tips",
  GOV2_REFERENDUM: "referenda",
  FELLOWSHIP_REFERENDUM: "fellowship/referenda",
  ADVISORY_MOTION: "advisory-committee/motions",
  ALLIANCE_MOTION: "alliance/motions",
  ALLIANCE_ANNOUNCEMENT: "alliance/announcements",
  TREASURY_COUNCIL_MOTION: "treasury-council/motion",
  OPEN_TECH_COMM_PROPOSAL: "open-techcomm/proposal",
};

export default businessCategory;
