import { nodes } from "./constants";
const configList = [
  {
    id: 1000,
    name: "AssetHub",
    key: "polkadot-assethub",
    website: "",
    github: "https://github.com/paritytech/polkadot-sdk",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 1001,
    name: "Collectives",
    key: "collectives",
    website: "",
    github: "https://github.com/paritytech/polkadot-sdk",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 1002,
    name: "BridgeHub",
    website: "",
    github: "https://github.com/paritytech/polkadot-sdk",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 1004,
    name: "People",
    website: "",
    github: "https://github.com/paritytech/polkadot-sdk",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 1005,
    name: "Coretime",
    website: "",
    github: "https://github.com/paritytech/polkadot-sdk",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2002,
    name: "Clover",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2004,
    name: "Moonbeam",
    website: "https://moonbeam.network/",
    github: "https://github.com/moonbeam-foundation/moonbeam",
    twitter: "https://x.com/MoonbeamNetwork",
    discord: "https://discord.com/invite/PfpUATX",
    telegram: "https://t.me/Moonbeam_Official",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2006,
    name: "Astar",
    key: "astar",
    website: "https://astar.network/",
    github: "https://github.com/AstarNetwork",
    twitter: "https://x.com/AstarNetwork",
    discord: "https://discord.com/invite/astarnetwork",
    telegram: "https://t.me/PlasmOfficial",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2008,
    name: "Crust",
    key: "crust",
    website: "https://www.crust.network/",
    github: "",
    twitter: "https://x.com/CrustNetwork",
    discord: "https://discord.com/invite/Jbw2PAUSCR",
    telegram: "https://t.me/CrustNetwork",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2012,
    name: "Parallel",
    website: "https://nirvana-finance.io/",
    github: "",
    twitter: "https://x.com/ParallelLabs_",
    discord: "https://discord.com/invite/parallelfi",
    telegram: "https://t.me/parallelfi_community",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2013,
    name: "Heima",
    key: "litentry",
    website: "https://www.heima.network/",
    github: "https://github.com/litentry/heima",
    twitter: "https://x.com/heimaNetwork",
    discord: "https://discord.com/invite/heima-network",
    telegram: "https://t.me/heima_network",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2019,
    name: "Composable Finance",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2025,
    name: "SORA",
    website: "",
    github: "https://github.com/sora-xor",
    twitter: "https://x.com/sora_xor",
    discord: "https://discord.com/invite/4TXRN6Y4gb",
    telegram: "https://t.me/sora_xor",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2026,
    name: "Nodle",
    website: "https://www.nodle.com/",
    github: "",
    twitter: "https://x.com/NodleNetwork",
    discord: "https://discord.com/invite/N5nTUt8RWJ",
    telegram: "https://telegram.me/nodlecommunity",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2030,
    name: "Bifrost",
    key: "bifrost-polkadot",
    website: "https://bifrost.io/",
    github: "https://github.com/bifrost-io",
    twitter: "https://x.com/Bifrost",
    discord: "https://discord.com/invite/bifrost",
    telegram: "https://t.me/bifrost_io",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2031,
    name: "Centrifuge",
    key: "centrifuge",
    website: "https://centrifuge.io/",
    github: "https://github.com/centrifuge/",
    twitter: "https://x.com/centrifuge",
    discord: "https://discord.com/invite/yEzyUq5gxF",
    telegram: "https://t.me/centrifuge_chat",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2032,
    name: "Interlay",
    key: "interlay",
    website: "https://www.interlay.io/",
    github: "",
    twitter: "https://x.com/InterlayHQ",
    discord: "https://discord.com/invite/interlay",
    telegram: "https://t.me/interlay_community",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2034,
    name: "Hydration",
    website: "https://hydration.net/",
    github: "https://github.com/galacticcouncil",
    twitter: "https://x.com/hydration_net",
    discord: "https://discord.com/invite/kkmY35UxAG",
    telegram: "https://t.me/hydration_net",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2035,
    name: "Phala Network",
    key: "phala",
    website: "https://phala.network/",
    github: "https://github.com/Phala-Network/",
    twitter: "https://x.com/PhalaNetwork",
    discord: "https://discord.com/invite/phala-network",
    telegram: "https://t.me/phalanetwork",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2037,
    name: "Unique Network",
    website: "https://unqnft.io/market",
    github: "https://github.com/UniqueNetwork",
    twitter: "https://x.com/Unique_NFTchain",
    discord: "https://discord.com/invite/jHVdZhsakC",
    telegram: "https://t.me/Uniquechain",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2039,
    name: "Integritee Network",
    website: "https://www.integritee.network/",
    github: "https://github.com/integritee-network",
    twitter: "https://x.com/integri_t_e_e",
    discord: "https://discord.com/invite/ZJJEScBpp9",
    telegram: "https://t.me/Integritee_Official",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2043,
    name: "NeuroWeb",
    website: "https://neuroweb.ai/",
    github: "",
    twitter: "https://x.com/NeuroWebAI",
    discord: "",
    telegram: "https://t.me/OriginTrail",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2046,
    name: "Darwinia",
    website: "https://darwinia.network/",
    github: "https://github.com/darwinia-network",
    twitter: "https://x.com/DarwiniaNetwork",
    discord: "https://discord.com/invite/rMRWY52AaJ",
    telegram: "https://t.me/DarwiniaNetwork",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2051,
    name: "Ajuna Network",
    key: "ajuna",
    website: "https://www.ajuna.io/",
    github: "https://github.com/ajuna-network/",
    twitter: "https://x.com/AjunaNetwork",
    discord: "https://discord.com/invite/ajuna-network",
    telegram: "https://t.me/ajunacommunity",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2086,
    name: "KILT Spiritnet",
    website: "https://www.kilt.io/",
    github: "https://github.com/KILTprotocol",
    twitter: "https://x.com/Kiltprotocol",
    discord: "https://discord.com/invite/HztRqvzbhG",
    telegram: "https://t.me/KILTProtocolChat",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2090,
    name: "OAK Network",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2091,
    name: "Frequency",
    website: "https://www.frequency.xyz/",
    github: "",
    twitter: "https://x.com/frequency_xyz",
    discord: "https://discord.com/invite/JchmHX5afV",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2092,
    name: "Zeitgeist",
    website: "https://zeitgeist.pm/",
    github: "https://github.com/ZeitgeistPM",
    twitter: "https://x.com/ZeitgeistPM",
    discord: "https://discord.com/invite/xv8HuA4s8v",
    telegram: "https://t.me/zeitgeist_official",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 2104,
    name: "Manta",
    website: "https://manta.network/",
    github: "https://github.com/manta-network",
    twitter: "https://x.com/MantaNetwork",
    discord: "https://discord.com/invite/mantanetwork",
    telegram: "https://www.t.me/mantanetworkofficial",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3338,
    name: "peaq",
    website: "https://www.peaq.network/",
    github: "https://github.com/peaqnetwork",
    twitter: "https://x.com/peaq",
    discord: "https://discord.com/invite/peaqnetwork",
    telegram: "https://t.me/peaqnetwork",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3340,
    name: "InvArch",
    website: "https://invarch.network/",
    github: "https://github.com/AbstractedCo/InvArch",
    twitter: "https://x.com/InvArchNetwork",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3344,
    name: "Polimec",
    website: "https://polimec.org",
    github: "https://github.com/Polimec",
    twitter: "https://x.com/PolimecProtocol",
    discord: "https://discord.com/invite/4CZh8HNVuT",
    telegram: "https://t.me/PolimecProtocol",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3345,
    name: "Energy Web X",
    website: "https://www.energywebx.com/",
    github: "",
    twitter: "https://x.com/XEnergyWeb",
    discord: "https://discord.com/invite/energyweb-706103009205288990",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3346,
    name: "Continuum",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3354,
    name: "Logion",
    website: "https://logion.network/",
    github: "https://github.com/logion-network",
    twitter: "https://x.com/logion_network",
    discord: "https://discord.com/invite/FvnxrtCYr6",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3367,
    name: "Hyperbridge (Nexus)",
    website: "https://hyperbridge.network/",
    github: "",
    twitter: "https://x.com/hyperbridge",
    discord: "https://discord.com/invite/WYTUQrTR9y",
    telegram: "https://t.me/hyper_bridge",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3370,
    name: "Laos",
    key: "laos",
    website: "https://www.laosnetwork.io/",
    github: "https://github.com/freeverseio/laos",
    twitter: "https://x.com/laosnetwork",
    discord: "https://discord.com/invite/gZcxsJcdPy",
    telegram: "https://t.me/+qI2I19EI-VAzNGVk",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3388,
    name: "Robonomics",
    website: "https://robonomics.network/",
    github: "https://github.com/airalab",
    twitter: "https://x.com/AIRA_Robonomics",
    discord: "https://discord.com/invite/J57BHwpteR",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3397,
    name: "JAMTON",
    website: "",
    github: "",
    twitter: "https://x.com/JamtonNetwork",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3366,
    name: "-",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3373,
    name: "-",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3377,
    name: "-",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
  {
    id: 3389,
    name: "-",
    website: "",
    github: "",
    twitter: "",
    discord: "",
    telegram: "",
    youtube: "",
    element: "",
    medium: "",
    reddit: "",
    substack: "",
    linkedin: "",
  },
].map((item) => {
  item.subsquareLink = "";
  const matchNode = nodes.find((i) => i.value === item.key);
  if (matchNode) {
    item.subsquareLink = `https://${
      matchNode.domain || matchNode.value
    }.subsquare.io${matchNode.isAssetHubNode ? "/assethub" : ""}`;
  }
  return item;
});

const parachainConfig = configList.reduce((result, item) => {
  const externalLink = [];
  item.website && externalLink.push({ type: "website", link: item.website });
  item.github && externalLink.push({ type: "github", link: item.github });
  item.twitter && externalLink.push({ type: "twitter", link: item.twitter });
  item.discord && externalLink.push({ type: "discord", link: item.discord });

  item.externalLink = externalLink;
  result[item.id] = item;
  return result;
}, {});

export default parachainConfig;
